In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 时间上的动态展开
n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, shape=[None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype = tf.float32)
init = tf.global_variables_initializer()

X_batch = np.array([
                   # t = 0    t = 1
                    [[0, 1, 2], [9, 8, 7]],  # instance 1
                    [[3, 4, 5], [0, 0, 0]],  # instance 2
                    [[6, 7, 8], [6, 5, 4]],  # instance 3
                    [[9, 0, 1], [3, 2, 1]],  # instance 4
                   ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X:X_batch})
print(outputs_val)




[[[ 0.85253745 -0.8635251  -0.8635848   0.85458994  0.18037374]
  [ 0.9651979  -0.9999984  -0.9994116   0.9999966   0.9999922 ]]

 [[ 0.98725057 -0.9993861  -0.995211    0.99890435  0.968388  ]
  [-0.59401023 -0.15162963  0.14211236  0.7379825   0.36245817]]

 [[ 0.9989663  -0.9999977  -0.99984264  0.99999243  0.9992574 ]
  [ 0.51020414 -0.99964994 -0.95994073  0.9998197   0.9992633 ]]

 [[-0.99981165  0.09574474  0.99207497  0.01269183  0.9952386 ]
  [ 0.09294475 -0.9053012  -0.33951876  0.79274285  0.04489781]]]
